// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

class UserEntitie {
  UserEntitie(
    this.password,
    this.message,
  );

  final String password;
  final String message;

  Map<String, dynamic> toMap() {
    return {
      'password': password,
      'message': message,
    };
  }

  factory UserEntitie.fromMap(Map<String, dynamic> map) {
    T cast<T>(String key) {
      if (map.containsKey(key)) {
        if (map[key] is T) {
          return map[key] as T;
        } else {
          throw ArgumentError.value(
            map[key],
            key,
            'Expected type $T but got ${map[key].runtimeType}',
          );
        }
      } else {
        throw ArgumentError.notNull(key);
      }
    }

    return UserEntitie(
      cast<String>('password'),
      map['message'] as String,
    );
  }

  String toJson() => json.encode(toMap());

  factory UserEntitie.fromJson(String source) =>
      UserEntitie.fromMap(json.decode(source) as Map<String, dynamic>);
}
